spring:
  application:
    name: orders-consumer

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: orders-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8082